# Generated by Django 5.1.5 on 2025-02-01 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviestore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('genre', models.TextField()),
                ('overview', models.TextField()),
                ('release_date', models.DateField()),
                ('image_url', models.URLField()),
            ],
        ),
    ]
