# Generated by Django 4.2.19 on 2025-02-15 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0003_review_rating_alter_review_user"),
        ("cart", "0002_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="movie",
            field=models.ManyToManyField(through="cart.Item", to="movies.movie"),
        ),
    ]
